server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"


build:
  version: "5.0"

loans:
  message: "Welcome to EazyBank Loans related local APIs "
  contactDetails:
    name: "Tony Stark"
    email: "tony.stark@eb.com"
  onCallSupport:
    - (412) 520-4575
    - (915) 520-6547
    - (415) 520-6547